version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 20

  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/web-frontend"
    schedule:
      interval: weekly
      day: wednesday
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
