version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/web/src/main/vite-project"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/Oslo
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
