apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: dftjen
  name: dev-kostra-kontrollprogram
  namespace: dftjen
spec:
  # application settings
  ingresses:
    - https://dev-kostra-kontrollprogram.intern.test.ssb.no
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 160Mi
