package no.ssb.kostra.area.famvern.famvern53

object Familievern53ColumnNames {
    const val FYLKE_NR_COL_NAME = "FYLKE_NR"
    const val KONTORNR_COL_NAME = "KONTORNR"
    const val TILTAK_PUBLIKUM_TILTAK_COL_NAME = "TILTAK_PUBLIKUM_TILTAK"
    const val TILTAK_PUBLIKUM_TIMER_COL_NAME = "TILTAK_PUBLIKUM_TIMER"
    const val VEILEDNING_STUDENTER_TILTAK_COL_NAME = "VEILEDNING_STUDENTER_TILTAK"
    const val VEILEDNING_STUDENTER_TIMER_COL_NAME = "VEILEDNING_STUDENTER_TIMER"
    const val VEILEDNING_HJELPEAP_TILTAK_COL_NAME = "VEILEDNING_HJELPEAP_TILTAK"
    const val VEILEDNING_HJELPEAP_TIMER_COL_NAME = "VEILEDNING_HJELPEAP_TIMER"
    const val INFO_MEDIA_TILTAK_COL_NAME = "INFO_MEDIA_TILTAK"
    const val INFO_MEDIA_TIMER_COL_NAME = "INFO_MEDIA_TIMER"
    const val TILSYN_TILTAK_COL_NAME = "TILSYN_TILTAK"
    const val TILSYN_TIMER_COL_NAME = "TILSYN_TIMER"
    const val FORELDREVEIL_TILTAK_COL_NAME = "FORELDREVEIL_TILTAK"
    const val FORELDREVEIL_TIMER_COL_NAME = "FORELDREVEIL_TIMER"
    const val ANNET_TILTAK_COL_NAME = "ANNET_TILTAK"
    const val ANNET_TIMER_COL_NAME = "ANNET_TIMER"
}