package no.ssb.kostra.control.famvern.s55;

import no.ssb.kostra.control.FieldDefinition;

import java.util.List;

public class FieldDefinitions {
    public static List<FieldDefinition> getFieldDefinitions() {
        return List.of(
                new FieldDefinition(1, "FYLKE_NR",
                        "String",
                        "textBox",
                        1, 2
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(2, "FYLKE_NAVN",
                        "String",
                        "textBox",
                        3, 22
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(31, "MEKLING_SEP_1",
                        "Integer",
                        "textBox",
                        23, 25
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(32, "MEKLING_SEP_2",
                        "Integer",
                        "textBox",
                        26, 28
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(33, "MEKLING_SEP_3",
                        "Integer",
                        "textBox",
                        29, 31
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(34, "MEKLING_SEP_TOT",
                        "Integer",
                        "textBox",
                        32, 35
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(35, "MEKLING_SEP_AVLYST",
                        "Integer",
                        "textBox",
                        36, 37
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(36, "MEKLING_SAM_1",
                        "Integer",
                        "textBox",
                        38, 40
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(37, "MEKLING_SAM_2",
                        "Integer",
                        "textBox",
                        41, 43
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(38, "MEKLING_SAM_3",
                        "Integer",
                        "textBox",
                        44, 46
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(39, "MEKLING_SAM_TOT",
                        "Integer",
                        "textBox",
                        47, 50
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(310, "MEKLING_SAM_AVLYST",
                        "Integer",
                        "textBox",
                        51, 52
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(311, "MEKLING_SAK_1",
                        "Integer",
                        "textBox",
                        53, 55
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(312, "MEKLING_SAK_2",
                        "Integer",
                        "textBox",
                        56, 58
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(313, "MEKLING_SAK_3",
                        "Integer",
                        "textBox",
                        59, 61
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(314, "MEKLING_SAK_TOT",
                        "Integer",
                        "textBox",
                        62, 65
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(315, "MEKLING_SAK_AVLYST",
                        "Integer",
                        "textBox",
                        66, 67
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(316, "MEKLING_TILB_1",
                        "Integer",
                        "textBox",
                        68, 69
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(317, "MEKLING_TILB_2",
                        "Integer",
                        "textBox",
                        70, 71
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(318, "MEKLING_TILB_3",
                        "Integer",
                        "textBox",
                        72, 73
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(319, "MEKLING_TILB_TOT",
                        "Integer",
                        "textBox",
                        74, 76
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(320, "MEKLING_TILB_AVLYST",
                        "Integer",
                        "textBox",
                        77, 78
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(321, "MEKLING_FLY_1",
                        "Integer",
                        "textBox",
                        79, 81
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(322, "MEKLING_FLY_2",
                        "Integer",
                        "textBox",
                        82, 84
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(323, "MEKLING_FLY_3",
                        "Integer",
                        "textBox",
                        85, 87
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(324, "MEKLING_FLY_TOT",
                        "Integer",
                        "textBox",
                        88, 91
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(325, "MEKLING_FLY_AVLYST",
                        "Integer",
                        "textBox",
                        92, 94
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(326, "MEKLING_TOT_1",
                        "Integer",
                        "textBox",
                        95, 98
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(327, "MEKLING_TOT_2",
                        "Integer",
                        "textBox",
                        99, 102
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(328, "MEKLING_TOT_3",
                        "Integer",
                        "textBox",
                        103, 106
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(329, "MEKLING_TOT_ALLE",
                        "Integer",
                        "textBox",
                        107, 110
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(330, "MEKLING_TOT_AVLYST",
                        "Integer",
                        "textBox",
                        111, 113
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(41, "SEP_BEGGE",
                        "Integer",
                        "textBox",
                        114, 116
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(42, "SEP_EN",
                        "Integer",
                        "textBox",
                        117, 119
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(43, "SEP_TOT",
                        "Integer",
                        "textBox",
                        120, 123
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(44, "SAM_BEGGE",
                        "Integer",
                        "textBox",
                        124, 126
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(45, "SAM_EN",
                        "Integer",
                        "textBox",
                        127, 129
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(46, "SAM_TOT",
                        "Integer",
                        "textBox",
                        130, 133
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(47, "SAK_BEGGE",
                        "Integer",
                        "textBox",
                        134, 136
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(48, "SAK_EN",
                        "Integer",
                        "textBox",
                        137, 139
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(49, "SAK_TOT",
                        "Integer",
                        "textBox",
                        140, 143
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(410, "TILB_BEGGE",
                        "Integer",
                        "textBox",
                        144, 145
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(411, "TILB_EN",
                        "Integer",
                        "textBox",
                        146, 147
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(412, "TILB_TOT",
                        "Integer",
                        "textBox",
                        148, 150
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(413, "FLY_BEGGE",
                        "Integer",
                        "textBox",
                        151, 153
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(414, "FLY_EN",
                        "Integer",
                        "textBox",
                        154, 156
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(415, "FLY_TOT",
                        "Integer",
                        "textBox",
                        157, 160
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(416, "BEGGE_TOT",
                        "Integer",
                        "textBox",
                        161, 164
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(417, "EN_TOT",
                        "Integer",
                        "textBox",
                        165, 168
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(418, "ENBEGGE_TOT",
                        "Integer",
                        "textBox",
                        169, 172
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(51, "VENTETID_SEP_1",
                        "Integer",
                        "textBox",
                        173, 175
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(52, "VENTETID_SEP_2",
                        "Integer",
                        "textBox",
                        176, 178
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(53, "VENTETID_SEP_3",
                        "Integer",
                        "textBox",
                        179, 181
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(54, "VENTETID_SEP_4",
                        "Integer",
                        "textBox",
                        182, 184
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(55, "VENTETID_SEP_TOT",
                        "Integer",
                        "textBox",
                        185, 188
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(56, "VENTETID_SAM_1",
                        "Integer",
                        "textBox",
                        189, 191
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(57, "VENTETID_SAM_2",
                        "Integer",
                        "textBox",
                        192, 194
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(58, "VENTETID_SAM_3",
                        "Integer",
                        "textBox",
                        195, 197
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(59, "VENTETID_SAM_4",
                        "Integer",
                        "textBox",
                        198, 200
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(510, "VENTETID_SAM_TOT",
                        "Integer",
                        "textBox",
                        201, 204
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(511, "VENTETID_SAK_1",
                        "Integer",
                        "textBox",
                        205, 207
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(512, "VENTETID_SAK_2",
                        "Integer",
                        "textBox",
                        208, 210
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(513, "VENTETID_SAK_3",
                        "Integer",
                        "textBox",
                        211, 213
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(514, "VENTETID_SAK_4",
                        "Integer",
                        "textBox",
                        214, 216
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(515, "VENTETID_SAK_TOT",
                        "Integer",
                        "textBox",
                        217, 220
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(516, "VENTETID_TILB_1",
                        "Integer",
                        "textBox",
                        221, 222
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(517, "VENTETID_TILB_2",
                        "Integer",
                        "textBox",
                        223, 224
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(518, "VENTETID_TILB_3",
                        "Integer",
                        "textBox",
                        225, 226
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(519, "VENTETID_TILB_4",
                        "Integer",
                        "textBox",
                        227, 228
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(520, "VENTETID_TILB_TOT",
                        "Integer",
                        "textBox",
                        229, 231
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(521, "VENTETID_FLY_1",
                        "Integer",
                        "textBox",
                        232, 234
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(522, "VENTETID_FLY_2",
                        "Integer",
                        "textBox",
                        235, 237
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(523, "VENTETID_FLY_3",
                        "Integer",
                        "textBox",
                        238, 240
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(524, "VENTETID_FLY_4",
                        "Integer",
                        "textBox",
                        241, 243
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(525, "VENTETID_FLT_TOT",
                        "Integer",
                        "textBox",
                        244, 247
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(526, "VENTETID_TOT_1",
                        "Integer",
                        "textBox",
                        248, 251
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(527, "VENTETID_TOT_2",
                        "Integer",
                        "textBox",
                        252, 255
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(528, "VENTETID_TOT_3",
                        "Integer",
                        "textBox",
                        256, 259
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(529, "VENTETID_TOT_4",
                        "Integer",
                        "textBox",
                        260, 263
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(530, "VENTETID_TOT_TOT",
                        "Integer",
                        "textBox",
                        264, 267
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(61, "FORHOLD_MEKLER",
                        "Integer",
                        "textBox",
                        268, 270
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(62, "FORHOLD_KLIENT",
                        "Integer",
                        "textBox",
                        271, 273
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(63, "FORHOLD_TOT",
                        "Integer",
                        "textBox",
                        274, 277
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(71, "VARIGHET_SEP_1",
                        "Integer",
                        "textBox",
                        278, 280
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(72, "VARIGHET_SEP_2",
                        "Integer",
                        "textBox",
                        281, 283
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(73, "VARIGHET_SEP_3",
                        "Integer",
                        "textBox",
                        284, 286
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(74, "VARIGHET_SEP_TOT",
                        "Integer",
                        "textBox",
                        287, 290
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(75, "VARIGHET_SAM_1",
                        "Integer",
                        "textBox",
                        291, 293
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(76, "VARIGHET_SAM_2",
                        "Integer",
                        "textBox",
                        294, 296
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(77, "VARIGHET_SAM_3",
                        "Integer",
                        "textBox",
                        297, 299
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(78, "VARIGHET_SAM_TOT",
                        "Integer",
                        "textBox",
                        300, 303
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(79, "VARIGHET_SAK_1",
                        "Integer",
                        "textBox",
                        304, 306
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(710, "VARIGHET_SAK_2",
                        "Integer",
                        "textBox",
                        307, 309
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(711, "VARIGHET_SAK_3",
                        "Integer",
                        "textBox",
                        310, 312
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(712, "VARIGHET_SAK_TOT",
                        "Integer",
                        "textBox",
                        313, 316
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(713, "VARIGHET_TILB_1",
                        "Integer",
                        "textBox",
                        317, 318
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(714, "VARIGHET_TILB_2",
                        "Integer",
                        "textBox",
                        319, 320
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(715, "VARIGHET_TILB_3",
                        "Integer",
                        "textBox",
                        321, 322
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(716, "VARIGHET_TILB_TOT",
                        "Integer",
                        "textBox",
                        323, 325
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(717, "VARIGHET_FLY_1",
                        "Integer",
                        "textBox",
                        326, 328
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(718, "VARIGHET_FLY_2",
                        "Integer",
                        "textBox",
                        329, 331
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(719, "VARIGHET_FLY_3",
                        "Integer",
                        "textBox",
                        332, 334
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(720, "VARIGHET_FLY_TOT",
                        "Integer",
                        "textBox",
                        335, 338
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(721, "VARIGHET_TOT_1",
                        "Integer",
                        "textBox",
                        339, 342
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(722, "VARIGHET_TOT_2",
                        "Integer",
                        "textBox",
                        343, 346
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(723, "VARIGHET_TOT_3",
                        "Integer",
                        "textBox",
                        347, 350
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(724, "VARIGHET_TOT_TOT",
                        "Integer",
                        "textBox",
                        351, 354
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(81, "BARNDELT_SEP_TOT",
                        "Integer",
                        "textBox",
                        355, 357
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(82, "BARNDELT_SAM_TOT",
                        "Integer",
                        "textBox",
                        358, 360
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(83, "BARNDELT_SAK_TOT",
                        "Integer",
                        "textBox",
                        361, 363
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(84, "BARNDELT_TILB_TOT",
                        "Integer",
                        "textBox",
                        364, 365
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(85, "BARNDELT_FLY_TOT",
                        "Integer",
                        "textBox",
                        366, 368
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(86, "BARNDELT_TOT_TOT",
                        "Integer",
                        "textBox",
                        369, 372
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(91, "RESULT_SEP_1",
                        "Integer",
                        "textBox",
                        373, 375
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(92, "RESULT_SEP_2",
                        "Integer",
                        "textBox",
                        376, 378
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(93, "RESULT_SEP_3",
                        "Integer",
                        "textBox",
                        379, 381
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(94, "RESULT_SEP_TOT",
                        "Integer",
                        "textBox",
                        382, 385
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(95, "RESULT_SAM_1",
                        "Integer",
                        "textBox",
                        386, 388
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(96, "RESULT_SAM_2",
                        "Integer",
                        "textBox",
                        389, 391
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(97, "RESULT_SAM_3",
                        "Integer",
                        "textBox",
                        392, 394
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(98, "RESULT_SAM_TOT",
                        "Integer",
                        "textBox",
                        395, 398
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(99, "RESULT_SAK_1",
                        "Integer",
                        "textBox",
                        399, 401
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(910, "RESULT_SAK_2",
                        "Integer",
                        "textBox",
                        402, 404
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(911, "RESULT_SAK_3",
                        "Integer",
                        "textBox",
                        405, 407
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(912, "RESULT_SAK_TOT",
                        "Integer",
                        "textBox",
                        408, 411
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(913, "RESULT_TILB_1",
                        "Integer",
                        "textBox",
                        412, 413
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(914, "RESULT_TILB_2",
                        "Integer",
                        "textBox",
                        414, 415
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(915, "RESULT_TILB_3",
                        "Integer",
                        "textBox",
                        416, 417
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(916, "RESULT_TILB_TOT",
                        "Integer",
                        "textBox",
                        418, 420
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(917, "RESULT_FLY_1",
                        "Integer",
                        "textBox",
                        421, 423
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(918, "RESULT_FLY_2",
                        "Integer",
                        "textBox",
                        424, 426
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(919, "RESULT_FLY_3",
                        "Integer",
                        "textBox",
                        427, 429
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(920, "RESULT_FLY_TOT",
                        "Integer",
                        "textBox",
                        430, 433
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(921, "RESULT_TOT_1",
                        "Integer",
                        "textBox",
                        434, 437
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(922, "RESULT_TOT_2",
                        "Integer",
                        "textBox",
                        438, 441
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(923, "RESULT_TOT_3",
                        "Integer",
                        "textBox",
                        442, 445
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(924, "RESULT_TOT_TOT",
                        "Integer",
                        "textBox",
                        446, 449
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(101, "AVTALE_SEP_1",
                        "Integer",
                        "textBox",
                        450, 452
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(102, "AVTALE_SEP_2",
                        "Integer",
                        "textBox",
                        453, 455
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(103, "AVTALE_SEP_3",
                        "Integer",
                        "textBox",
                        456, 458
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(104, "AVTALE_SEP_TOT",
                        "Integer",
                        "textBox",
                        459, 462
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(105, "AVTALE_SAM_1",
                        "Integer",
                        "textBox",
                        463, 465
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(106, "AVTALE_SAM_2",
                        "Integer",
                        "textBox",
                        466, 468
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(107, "AVTALE_SAM_3",
                        "Integer",
                        "textBox",
                        469, 471
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(108, "AVTALE_SAM_TOT",
                        "Integer",
                        "textBox",
                        472, 475
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(109, "AVTALE_SAK_1",
                        "Integer",
                        "textBox",
                        476, 478
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1010, "AVTALE_SAK_2",
                        "Integer",
                        "textBox",
                        479, 481
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1011, "AVTALE_SAK_3",
                        "Integer",
                        "textBox",
                        482, 484
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1012, "AVTALE_SAK_TOT",
                        "Integer",
                        "textBox",
                        485, 488
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1013, "AVTALE_TILB_1",
                        "Integer",
                        "textBox",
                        489, 490
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1014, "AVTALE_TILB_2",
                        "Integer",
                        "textBox",
                        491, 492
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1015, "AVTALE_TILB_3",
                        "Integer",
                        "textBox",
                        493, 494
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1016, "AVTALE_TILB_TOT",
                        "Integer",
                        "textBox",
                        495, 497
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1017, "AVTALE_FLY_1",
                        "Integer",
                        "textBox",
                        498, 500
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1018, "AVTALE_FLY_2",
                        "Integer",
                        "textBox",
                        501, 503
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1019, "AVTALE_FLY_3",
                        "Integer",
                        "textBox",
                        504, 506
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1020, "AVTALE_FLY_TOT",
                        "Integer",
                        "textBox",
                        507, 510
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1021, "AVTALE_TOT_1",
                        "Integer",
                        "textBox",
                        511, 514
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1022, "AVTALE_TOT_2",
                        "Integer",
                        "textBox",
                        515, 518
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1023, "AVTALE_TOT_3",
                        "Integer",
                        "textBox",
                        519, 522
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1024, "AVTALE_TOT_TOT",
                        "Integer",
                        "textBox",
                        523, 526
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(111, "BEKYMR_SEP_1",
                        "Integer",
                        "textBox",
                        527, 529
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(112, "BEKYMR_SEP_2",
                        "Integer",
                        "textBox",
                        530, 532
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(113, "BEKYMR_SEP_TOT",
                        "Integer",
                        "textBox",
                        533, 536
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(114, "BEKYMR_SAM_1",
                        "Integer",
                        "textBox",
                        537, 539
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(115, "BEKYMR_SAM_2",
                        "Integer",
                        "textBox",
                        540, 542
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(116, "BEKYMR_SAM_TOT",
                        "Integer",
                        "textBox",
                        543, 546
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(117, "BEKYMR_SAK_1",
                        "Integer",
                        "textBox",
                        547, 549
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(118, "BEKYMR_SAK_2",
                        "Integer",
                        "textBox",
                        550, 552
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(119, "BEKYMR_SAK_TOT",
                        "Integer",
                        "textBox",
                        553, 556
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1110, "BEKYMR_TILB_1",
                        "Integer",
                        "textBox",
                        557, 558
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1111, "BEKYMR_TILB_2",
                        "Integer",
                        "textBox",
                        559, 560
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1112, "BEKYMR_TILB_TOT",
                        "Integer",
                        "textBox",
                        561, 563
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1113, "BEKYMR_FLY_1",
                        "Integer",
                        "textBox",
                        564, 566
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1114, "BEKYMR_FLY_2",
                        "Integer",
                        "textBox",
                        567, 569
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1115, "BEKYMR_FLY_TOT",
                        "Integer",
                        "textBox",
                        570, 573
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1116, "BEKYMR_TOT_1",
                        "Integer",
                        "textBox",
                        574, 577
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1117, "BEKYMR_TOT_2",
                        "Integer",
                        "textBox",
                        578, 581
                        , List.of(),
                        "",
                        false),
                new FieldDefinition(1118, "BEKYMR_TOT_TOT",
                        "Integer",
                        "textBox",
                        582, 585
                        , List.of(),
                        "",
                        false)
        );
    }

    public static Integer getFieldLength() {
        return getFieldDefinitions().get(getFieldDefinitions().size() - 1).getTo();
    }
}