package no.ssb.kostra.area.sosial.kvalifisering

object KvalifiseringColumnNames {

    const val SAKSBEHANDLER_COL_NAME = "SAKSBEHANDLER"
    const val PERSON_JOURNALNR_COL_NAME = "PERSON_JOURNALNR"
    const val PERSON_FODSELSNR_COL_NAME = "PERSON_FODSELSNR"

    const val KOMMUNE_NR_COL_NAME = "KOMMUNE_NR"
    const val BYDELSNR_COL_NAME = "BYDELSNR"
    const val DISTRIKTSNR_COL_NAME = "DISTRIKTSNR"
    const val VERSION_COL_NAME = "VERSION"

    const val KJONN_COL_NAME = "KJONN"
    const val STATUS_COL_NAME = "STATUS"
    const val AVSL_DATO_COL_NAME = "AVSL_DATO"
    const val EKTSTAT_COL_NAME = "EKTSTAT"

    const val HAR_BARN_UNDER_18_COL_NAME = "BU18"
    const val ANT_BARN_UNDER_18_COL_NAME = "ANTBU18"
    const val REG_DATO_COL_NAME = "REG_DATO"
    const val VEDTAK_DATO_COL_NAME = "VEDTAK_DATO"
    const val BEGYNT_DATO_COL_NAME = "BEGYNT_DATO"
    const val KVP_KOMM_COL_NAME = "KVP_KOMM"
    const val KOMMNR_KVP_KOMM_COL_NAME = "KOMMNR_KVP_KOMM"
    const val KVP_MED_ASTONAD_COL_NAME = "KVP_MED_ASTONAD"

    const val KVP_STONAD_COL_NAME = "KVP_STONAD"

    const val KVP_MED_KOMMBOS_COL_NAME = "KVP_MED_KOMMBOS"
    const val KVP_MED_HUSBANK_COL_NAME = "KVP_MED_HUSBANK"
    const val KVP_MED_SOSHJ_ENGANG_COL_NAME = "KVP_MED_SOSHJ_ENGANG"
    const val KVP_MED_SOSHJ_PGM_COL_NAME = "KVP_MED_SOSHJ_PGM"
    const val KVP_MED_SOSHJ_SUP_COL_NAME = "KVP_MED_SOSHJ_SUP"

    // CR NOTE: Not in use
    const val KVP_OSLO_COL_NAME = "KVP_OSLO"

    const val YTELSE_SOSHJELP_COL_NAME = "YTELSE_SOSHJELP"
    const val YTELSE_TYPE_SOSHJ_COL_NAME = "YTELSE_TYPE_SOSHJ"
    const val YTELSE_INTRO_COL_NAME = "YTELSE_INTRO"
    const val YTELSE_INDIVIDSTONAD_COL_NAME = "YTELSE_INDIVIDSTONAD"
    const val YTELSE_FOLKETRYGDL_COL_NAME = "YTELSE_FOLKETRYGDL"


    const val AVSL_ORDINAERTARB_COL_NAME = "AVSL_ORDINAERTARB"
    const val AVSL_ARBLONNSTILS_COL_NAME = "AVSL_ARBLONNSTILS"
    const val AVSL_ARBMARK_COL_NAME = "AVSL_ARBMARK"
    const val AVSL_SKOLE_COL_NAME = "AVSL_SKOLE"
    const val AVSL_UFORE_COL_NAME = "AVSL_UFORE"
    const val AVSL_AAP_COL_NAME = "AVSL_AAP"
    const val AVSL_OK_AVKLAR_COL_NAME = "AVSL_OK_AVKLAR"
    const val AVSL_UTEN_OK_AVKLAR_COL_NAME = "AVSL_UTEN_OK_AVKLAR"
    const val AVSL_ANNET_COL_NAME = "AVSL_ANNET"
    const val AVSL_UKJENT_COL_NAME = "AVSL_UKJENT"
    const val AVSL_VIKTIGSTE_INNTEKT_COL_NAME = "AVSL_VIKTIGSTE_INNTEKT"
}