package no.ssb.kostra.control.sosial.s11c_kvalifiseringsstonad;

import no.ssb.kostra.felles.Code;
import no.ssb.kostra.felles.FieldDefinition;

import java.util.List;

public class FieldDefinitions {
    public static List<FieldDefinition> getFieldDefinitions() {
        return List.of(
                new FieldDefinition(1,
                        "KOMMUNE_NR",
                        "String",
                        "textBox",
                        1, 4,
                        List.of(),
                        "",
                        true),
                new FieldDefinition(2,
                        "VERSION",
                        "String",
                        "textBox",
                        5, 6,
                        List.of(),
                        "",
                        true),
                new FieldDefinition(3,
                        "BYDELSNR",
                        "String",
                        "textBox",
                        7, 8,
                        List.of(),
                        "",
                        false),
                new FieldDefinition(4,
                        "DISTRIKTSNR",
                        "String",
                        "textBox",
                        9, 10,
                        List.of(),
                        "",
                        false),
                new FieldDefinition(5, "PERSON_JOURNALNR",
                        "String",
                        "textBox",
                        11, 18,
                        List.of(),
                        "",
                        false),
                new FieldDefinition(6, "PERSON_FODSELSNR",
                        "String",
                        "textBox",
                        19, 29,
                        List.of(),
                        "",
                        false),
                new FieldDefinition(7, "KJONN",
                        "String",
                        "dropDownList",
                        30, 30,
                        List.of(
                                new Code("1", "Mann"),
                                new Code("2", "Kvinne")),
                        "",
                        true),
                new FieldDefinition(8, "EKTSTAT",
                        "String",
                        "dropDownList",
                        31, 31,
                        List.of(
                                new Code("1", "Ugift"),
                                new Code("2", "Gift"),
                                new Code("3", "Samboer"),
                                new Code("4", "Skilt/separert"),
                                new Code("5", "Enke/enkemann")),
                        "",
                        false),
                new FieldDefinition(91, "BU18",
                        "String",
                        "dropDownList",
                        32, 32,
                        List.of(
                                new Code("1", "Ja"),
                                new Code("2", "Nei")),
                        "",
                        true),
                new FieldDefinition(92, "ANTBU18",
                        "Integer",
                        "textBox",
                        33, 34,
                        List.of(),
                        "",
                        false),
                new FieldDefinition(10, "REG_DATO",
                        "Date",
                        "textBox",
                        35, 40,
                        List.of(),
                        "ddMMyy",
                        true),
                new FieldDefinition(11, "VEDTAK_DATO",
                        "Date",
                        "textBox",
                        41, 46,
                        List.of(),
                        "ddMMyy",
                        true),
                new FieldDefinition(12, "BEGYNT_DATO",
                        "Date",
                        "textBox",
                        47, 52,
                        List.of(),
                        "ddMMyy",
                        true),
                new FieldDefinition(141, "KVP_KOMM",
                        "String",
                        "dropDownList",
                        53, 53,
                        List.of(
                                new Code("1", "Ja"),
                                new Code("2", "Nei")),
                        "",
                        false),
                new FieldDefinition(142, "KOMMNR_KVP_KOMM",
                        "String",
                        "textBox",
                        54, 57,
                        // hentet fra https://www.ssb.no/klass/klassifikasjoner/131
                        List.of(
                                new Code("0301", "Oslo"),
                                new Code("1101", "Eigersund"),
                                new Code("1103", "Stavanger"),
                                new Code("1106", "Haugesund"),
                                new Code("1108", "Sandnes"),
                                new Code("1111", "Sokndal"),
                                new Code("1112", "Lund"),
                                new Code("1114", "Bjerkreim"),
                                new Code("1119", "Hå"),
                                new Code("1120", "Klepp"),
                                new Code("1121", "Time"),
                                new Code("1122", "Gjesdal"),
                                new Code("1124", "Sola"),
                                new Code("1127", "Randaberg"),
                                new Code("1130", "Strand"),
                                new Code("1133", "Hjelmeland"),
                                new Code("1134", "Suldal"),
                                new Code("1135", "Sauda"),
                                new Code("1144", "Kvitsøy"),
                                new Code("1145", "Bokn"),
                                new Code("1146", "Tysvær"),
                                new Code("1149", "Karmøy"),
                                new Code("1151", "Utsira"),
                                new Code("1160", "Vindafjord"),
                                new Code("1505", "Kristiansund"),
                                new Code("1506", "Molde"),
                                new Code("1507", "Ålesund"),
                                new Code("1511", "Vanylven"),
                                new Code("1514", "Sande"),
                                new Code("1515", "Herøy (Møre og Romsdal)"),
                                new Code("1516", "Ulstein"),
                                new Code("1517", "Hareid"),
                                new Code("1520", "Ørsta"),
                                new Code("1525", "Stranda"),
                                new Code("1528", "Sykkylven"),
                                new Code("1531", "Sula"),
                                new Code("1532", "Giske"),
                                new Code("1535", "Vestnes"),
                                new Code("1539", "Rauma"),
                                new Code("1547", "Aukra"),
                                new Code("1554", "Averøy"),
                                new Code("1557", "Gjemnes"),
                                new Code("1560", "Tingvoll"),
                                new Code("1563", "Sunndal"),
                                new Code("1566", "Surnadal"),
                                new Code("1573", "Smøla"),
                                new Code("1576", "Aure"),
                                new Code("1577", "Volda"),
                                new Code("1578", "Fjord"),
                                new Code("1579", "Hustadvika"),
                                new Code("1804", "Bodø"),
                                new Code("1806", "Narvik"),
                                new Code("1811", "Bindal"),
                                new Code("1812", "Sømna"),
                                new Code("1813", "Brønnøy"),
                                new Code("1815", "Vega"),
                                new Code("1816", "Vevelstad"),
                                new Code("1818", "Herøy (Nordland)"),
                                new Code("1820", "Alstahaug"),
                                new Code("1822", "Leirfjord"),
                                new Code("1824", "Vefsn"),
                                new Code("1825", "Grane"),
                                new Code("1826", "Aarborte - Hattfjelldal"),
                                new Code("1827", "Dønna"),
                                new Code("1828", "Nesna"),
                                new Code("1832", "Hemnes"),
                                new Code("1833", "Rana"),
                                new Code("1834", "Lurøy"),
                                new Code("1835", "Træna"),
                                new Code("1836", "Rødøy"),
                                new Code("1837", "Meløy"),
                                new Code("1838", "Gildeskål"),
                                new Code("1839", "Beiarn"),
                                new Code("1840", "Saltdal"),
                                new Code("1841", "Fauske - Fuossko"),
                                new Code("1845", "Sørfold"),
                                new Code("1848", "Steigen"),
                                new Code("1851", "Lødingen"),
                                new Code("1853", "Evenes"),
                                new Code("1856", "Røst"),
                                new Code("1857", "Værøy"),
                                new Code("1859", "Flakstad"),
                                new Code("1860", "Vestvågøy"),
                                new Code("1865", "Vågan"),
                                new Code("1866", "Hadsel"),
                                new Code("1867", "Bø"),
                                new Code("1868", "Øksnes"),
                                new Code("1870", "Sortland"),
                                new Code("1871", "Andøy"),
                                new Code("1874", "Moskenes"),
                                new Code("1875", "Hamarøy"),
                                new Code("3001", "Halden"),
                                new Code("3002", "Moss"),
                                new Code("3003", "Sarpsborg"),
                                new Code("3004", "Fredrikstad"),
                                new Code("3005", "Drammen"),
                                new Code("3006", "Kongsberg"),
                                new Code("3007", "Ringerike"),
                                new Code("3011", "Hvaler"),
                                new Code("3012", "Aremark"),
                                new Code("3013", "Marker"),
                                new Code("3014", "Indre Østfold"),
                                new Code("3015", "Skiptvet"),
                                new Code("3016", "Rakkestad"),
                                new Code("3017", "Råde"),
                                new Code("3018", "Våler (Viken)"),
                                new Code("3019", "Vestby"),
                                new Code("3020", "Nordre Follo"),
                                new Code("3021", "Ås"),
                                new Code("3022", "Frogn"),
                                new Code("3023", "Nesodden"),
                                new Code("3024", "Bærum"),
                                new Code("3025", "Asker"),
                                new Code("3026", "Aurskog-Høland"),
                                new Code("3027", "Rælingen"),
                                new Code("3028", "Enebakk"),
                                new Code("3029", "Lørenskog"),
                                new Code("3030", "Lillestrøm"),
                                new Code("3031", "Nittedal"),
                                new Code("3032", "Gjerdrum"),
                                new Code("3033", "Ullensaker"),
                                new Code("3034", "Nes"),
                                new Code("3035", "Eidsvoll"),
                                new Code("3036", "Nannestad"),
                                new Code("3037", "Hurdal"),
                                new Code("3038", "Hole"),
                                new Code("3039", "Flå"),
                                new Code("3040", "Nesbyen"),
                                new Code("3041", "Gol"),
                                new Code("3042", "Hemsedal"),
                                new Code("3043", "Ål"),
                                new Code("3044", "Hol"),
                                new Code("3045", "Sigdal"),
                                new Code("3046", "Krødsherad"),
                                new Code("3047", "Modum"),
                                new Code("3048", "Øvre Eiker"),
                                new Code("3049", "Lier"),
                                new Code("3050", "Flesberg"),
                                new Code("3051", "Rollag"),
                                new Code("3052", "Nore og Uvdal"),
                                new Code("3053", "Jevnaker"),
                                new Code("3054", "Lunner"),
                                new Code("3401", "Kongsvinger"),
                                new Code("3403", "Hamar"),
                                new Code("3405", "Lillehammer"),
                                new Code("3407", "Gjøvik"),
                                new Code("3411", "Ringsaker"),
                                new Code("3412", "Løten"),
                                new Code("3413", "Stange"),
                                new Code("3414", "Nord-Odal"),
                                new Code("3415", "Sør-Odal"),
                                new Code("3416", "Eidskog"),
                                new Code("3417", "Grue"),
                                new Code("3418", "Åsnes"),
                                new Code("3419", "Våler (Innlandet)"),
                                new Code("3420", "Elverum"),
                                new Code("3421", "Trysil"),
                                new Code("3422", "Åmot"),
                                new Code("3423", "Stor-Elvdal"),
                                new Code("3424", "Rendalen"),
                                new Code("3425", "Engerdal"),
                                new Code("3426", "Tolga"),
                                new Code("3427", "Tynset"),
                                new Code("3428", "Alvdal"),
                                new Code("3429", "Folldal"),
                                new Code("3430", "Os"),
                                new Code("3431", "Dovre"),
                                new Code("3432", "Lesja"),
                                new Code("3433", "Skjåk"),
                                new Code("3434", "Lom"),
                                new Code("3435", "Vågå"),
                                new Code("3436", "Nord-Fron"),
                                new Code("3437", "Sel"),
                                new Code("3438", "Sør-Fron"),
                                new Code("3439", "Ringebu"),
                                new Code("3440", "Øyer"),
                                new Code("3441", "Gausdal"),
                                new Code("3442", "Østre Toten"),
                                new Code("3443", "Vestre Toten"),
                                new Code("3446", "Gran"),
                                new Code("3447", "Søndre Land"),
                                new Code("3448", "Nordre Land"),
                                new Code("3449", "Sør-Aurdal"),
                                new Code("3450", "Etnedal"),
                                new Code("3451", "Nord-Aurdal"),
                                new Code("3452", "Vestre Slidre"),
                                new Code("3453", "Øystre Slidre"),
                                new Code("3454", "Vang"),
                                new Code("3801", "Horten"),
                                new Code("3802", "Holmestrand"),
                                new Code("3803", "Tønsberg"),
                                new Code("3804", "Sandefjord"),
                                new Code("3805", "Larvik"),
                                new Code("3806", "Porsgrunn"),
                                new Code("3807", "Skien"),
                                new Code("3808", "Notodden"),
                                new Code("3811", "Færder"),
                                new Code("3812", "Siljan"),
                                new Code("3813", "Bamble"),
                                new Code("3814", "Kragerø"),
                                new Code("3815", "Drangedal"),
                                new Code("3816", "Nome"),
                                new Code("3817", "Midt-Telemark"),
                                new Code("3818", "Tinn"),
                                new Code("3819", "Hjartdal"),
                                new Code("3820", "Seljord"),
                                new Code("3821", "Kviteseid"),
                                new Code("3822", "Nissedal"),
                                new Code("3823", "Fyresdal"),
                                new Code("3824", "Tokke"),
                                new Code("3825", "Vinje"),
                                new Code("4201", "Risør"),
                                new Code("4202", "Grimstad"),
                                new Code("4203", "Arendal"),
                                new Code("4204", "Kristiansand"),
                                new Code("4205", "Lindesnes"),
                                new Code("4206", "Farsund"),
                                new Code("4207", "Flekkefjord"),
                                new Code("4211", "Gjerstad"),
                                new Code("4212", "Vegårshei"),
                                new Code("4213", "Tvedestrand"),
                                new Code("4214", "Froland"),
                                new Code("4215", "Lillesand"),
                                new Code("4216", "Birkenes"),
                                new Code("4217", "Åmli"),
                                new Code("4218", "Iveland"),
                                new Code("4219", "Evje og Hornnes"),
                                new Code("4220", "Bygland"),
                                new Code("4221", "Valle"),
                                new Code("4222", "Bykle"),
                                new Code("4223", "Vennesla"),
                                new Code("4224", "Åseral"),
                                new Code("4225", "Lyngdal"),
                                new Code("4226", "Hægebostad"),
                                new Code("4227", "Kvinesdal"),
                                new Code("4228", "Sirdal"),
                                new Code("4601", "Bergen"),
                                new Code("4602", "Kinn"),
                                new Code("4611", "Etne"),
                                new Code("4612", "Sveio"),
                                new Code("4613", "Bømlo"),
                                new Code("4614", "Stord"),
                                new Code("4615", "Fitjar"),
                                new Code("4616", "Tysnes"),
                                new Code("4617", "Kvinnherad"),
                                new Code("4618", "Ullensvang"),
                                new Code("4619", "Eidfjord"),
                                new Code("4620", "Ulvik"),
                                new Code("4621", "Voss"),
                                new Code("4622", "Kvam"),
                                new Code("4623", "Samnanger"),
                                new Code("4624", "Bjørnafjorden"),
                                new Code("4625", "Austevoll"),
                                new Code("4626", "Øygarden"),
                                new Code("4627", "Askøy"),
                                new Code("4628", "Vaksdal"),
                                new Code("4629", "Modalen"),
                                new Code("4630", "Osterøy"),
                                new Code("4631", "Alver"),
                                new Code("4632", "Austrheim"),
                                new Code("4633", "Fedje"),
                                new Code("4634", "Masfjorden"),
                                new Code("4635", "Gulen"),
                                new Code("4636", "Solund"),
                                new Code("4637", "Hyllestad"),
                                new Code("4638", "Høyanger"),
                                new Code("4639", "Vik"),
                                new Code("4640", "Sogndal"),
                                new Code("4641", "Aurland"),
                                new Code("4642", "Lærdal"),
                                new Code("4643", "Årdal"),
                                new Code("4644", "Luster"),
                                new Code("4645", "Askvoll"),
                                new Code("4646", "Fjaler"),
                                new Code("4647", "Sunnfjord"),
                                new Code("4648", "Bremanger"),
                                new Code("4649", "Stad"),
                                new Code("4650", "Gloppen"),
                                new Code("4651", "Stryn"),
                                new Code("5001", "Trondheim"),
                                new Code("5006", "Steinkjer"),
                                new Code("5007", "Namsos"),
                                new Code("5014", "Frøya"),
                                new Code("5020", "Osen"),
                                new Code("5021", "Oppdal"),
                                new Code("5022", "Rennebu"),
                                new Code("5025", "Røros"),
                                new Code("5026", "Holtålen"),
                                new Code("5027", "Midtre Gauldal"),
                                new Code("5028", "Melhus"),
                                new Code("5029", "Skaun"),
                                new Code("5031", "Malvik"),
                                new Code("5032", "Selbu"),
                                new Code("5033", "Tydal"),
                                new Code("5034", "Meråker"),
                                new Code("5035", "Stjørdal"),
                                new Code("5036", "Frosta"),
                                new Code("5037", "Levanger"),
                                new Code("5038", "Verdal"),
                                new Code("5041", "Snåase - Snåsa"),
                                new Code("5042", "Lierne"),
                                new Code("5043", "Raarvihke - Røyrvik"),
                                new Code("5044", "Namsskogan"),
                                new Code("5045", "Grong"),
                                new Code("5046", "Høylandet"),
                                new Code("5047", "Overhalla"),
                                new Code("5049", "Flatanger"),
                                new Code("5052", "Leka"),
                                new Code("5053", "Inderøy"),
                                new Code("5054", "Indre Fosen"),
                                new Code("5055", "Heim"),
                                new Code("5056", "Hitra"),
                                new Code("5057", "Ørland"),
                                new Code("5058", "Åfjord"),
                                new Code("5059", "Orkland"),
                                new Code("5060", "Nærøysund"),
                                new Code("5061", "Rindal"),
                                new Code("5401", "Tromsø"),
                                new Code("5402", "Harstad"),
                                new Code("5403", "Alta"),
                                new Code("5404", "Vardø"),
                                new Code("5405", "Vadsø"),
                                new Code("5406", "Hammerfest"),
                                new Code("5411", "Kvæfjord"),
                                new Code("5412", "Tjeldsund"),
                                new Code("5413", "Ibestad"),
                                new Code("5414", "Gratangen"),
                                new Code("5415", "Loabák - Lavangen"),
                                new Code("5416", "Bardu"),
                                new Code("5417", "Salangen"),
                                new Code("5418", "Målselv"),
                                new Code("5419", "Sørreisa"),
                                new Code("5420", "Dyrøy"),
                                new Code("5421", "Senja"),
                                new Code("5422", "Balsfjord"),
                                new Code("5423", "Karlsøy"),
                                new Code("5424", "Lyngen"),
                                new Code("5425", "Storfjord - Omasvuotna - Omasvuono"),
                                new Code("5426", "Gáivuotna - Kåfjord - Kaivuono"),
                                new Code("5427", "Skjervøy"),
                                new Code("5428", "Nordreisa"),
                                new Code("5429", "Kvænangen"),
                                new Code("5430", "Guovdageaidnu - Kautokeino"),
                                new Code("5432", "Loppa"),
                                new Code("5433", "Hasvik"),
                                new Code("5434", "Måsøy"),
                                new Code("5435", "Nordkapp"),
                                new Code("5436", "Porsanger - Porsáŋgu - Porsanki"),
                                new Code("5437", "Kárášjohka - Karasjok"),
                                new Code("5438", "Lebesby"),
                                new Code("5439", "Gamvik"),
                                new Code("5440", "Berlevåg"),
                                new Code("5441", "Deatnu - Tana"),
                                new Code("5442", "Unjárga - Nesseby"),
                                new Code("5443", "Båtsfjord"),
                                new Code("5444", "Sør-Varanger")
                        ),
                        "",
                        false),
                new FieldDefinition(143, "KVP_OSLO",
                        "String",
                        "dropDownList",
                        58, 58,
                        List.of(
                                new Code("1", "Ja"),
                                new Code("2", "Nei")),
                        "",
                        false),
                new FieldDefinition(151, "YTELSE_SOSHJELP",
                        "String",
                        "checkBox",
                        59, 59,
                        List.of(
                                new Code("1", "Sosialhjelp")),
                        "",
                        false),
                new FieldDefinition(152, "YTELSE_TYPE_SOSHJ",
                        "String",
                        "dropDownList",
                        60, 60,
                        List.of(
                                new Code("2", "Sosialhjelp som viktigste kilde til livsopphold"),
                                new Code("3", "Supplerende sosialhjelp")),
                        "",
                        false),
                new FieldDefinition(153, "YTELSE_INTRO",
                        "String",
                        "checkBox",
                        61, 61,
                        List.of(
                                new Code("4", "Introduksjonsstønad")),
                        "",
                        false),
                new FieldDefinition(154, "YTELSE_INDIVIDSTONAD",
                        "String",
                        "checkBox",
                        62, 62,
                        List.of(
                                new Code("5", "Individstønad - stønad til livsopphold etter forskrift om arbeidsmarkedstiltak")),
                        "",
                        false),
                new FieldDefinition(155, "YTELSE_FOLKETRYGDL",
                        "String",
                        "checkBox",
                        63, 63,
                        List.of(
                                new Code("6", "Livsoppholdsytelse etter folketrygdloven - jf veiledningen")),
                        "",
                        false),
                new FieldDefinition(201, "KVP_MED_ASTONAD",
                        "String",
                        "dropDownList",
                        64, 64,
                        List.of(
                                new Code("1", "Ja"),
                                new Code("2", "Nei")),
                        "",
                        false),
                new FieldDefinition(202, "KVP_MED_KOMMBOS",
                        "String",
                        "checkBox",
                        65, 65,
                        List.of(
                                new Code("4", "Kommunal bostøtte")),
                        "",
                        false),
                new FieldDefinition(203, "KVP_MED_HUSBANK",
                        "String",
                        "checkBox",
                        66, 66,
                        List.of(
                                new Code("5", "Husbankens bostøtte")),
                        "",
                        false),
                new FieldDefinition(204, "KVP_MED_SOSHJ_ENGANG",
                        "String",
                        "checkBox",
                        67, 67,
                        List.of(
                                new Code("9", "Mottok økonomisk sosialhjelp som engangsstønad")),
                        "",
                        false),
                new FieldDefinition(205, "KVP_MED_SOSHJ_PGM",
                        "String",
                        "checkBox",
                        68, 68,
                        List.of(
                                new Code("8", "Mottok økonomisk sosialhjelp til dekking av særskilte utgifter knyttet til deltakelsen i programmet")),
                        "",
                        false),
                new FieldDefinition(206, "KVP_MED_SOSHJ_SUP",
                        "String",
                        "checkBox",
                        69, 69,
                        List.of(
                                new Code("7", "Mottok økonomisk sosialhjelp som fast supplement til dekking av løpende livsholdsutgifter")),
                        "",
                        false),
                new FieldDefinition(211, "STMND_1",
                        "String",
                        "checkBox",
                        70, 71,
                        List.of(
                                new Code("01", "Januar")),
                        "",
                        false),
                new FieldDefinition(212, "STMND_2",
                        "String",
                        "checkBox",
                        72, 73,
                        List.of(
                                new Code("02", "Februar")),
                        "",
                        false),
                new FieldDefinition(213, "STMND_3",
                        "String",
                        "checkBox",
                        74, 75,
                        List.of(
                                new Code("03", "Mars")),
                        "",
                        false),
                new FieldDefinition(214, "STMND_4",
                        "String",
                        "checkBox",
                        76, 77,
                        List.of(
                                new Code("04", "April")),
                        "",
                        false),
                new FieldDefinition(215, "STMND_5",
                        "String",
                        "checkBox",
                        78, 79,
                        List.of(
                                new Code("05", "Mai")),
                        "",
                        false),
                new FieldDefinition(216, "STMND_6",
                        "String",
                        "checkBox",
                        80, 81,
                        List.of(
                                new Code("06", "Juni")),
                        "",
                        false),
                new FieldDefinition(217, "STMND_7",
                        "String",
                        "checkBox",
                        82, 83,
                        List.of(
                                new Code("07", "Juli")),
                        "",
                        false),
                new FieldDefinition(218, "STMND_8",
                        "String",
                        "checkBox",
                        84, 85,
                        List.of(
                                new Code("08", "August")),
                        "",
                        false),
                new FieldDefinition(219, "STMND_9",
                        "String",
                        "checkBox",
                        86, 87,
                        List.of(
                                new Code("09", "September")),
                        "",
                        false),
                new FieldDefinition(2110, "STMND_10",
                        "String",
                        "checkBox",
                        88, 89,
                        List.of(
                                new Code("10", "Oktober")),
                        "",
                        false),
                new FieldDefinition(2111, "STMND_11",
                        "String",
                        "checkBox",
                        90, 91,
                        List.of(
                                new Code("11", "November")),
                        "",
                        false),
                new FieldDefinition(2112, "STMND_12",
                        "String",
                        "checkBox",
                        92, 93,
                        List.of(
                                new Code("12", "Desember")),
                        "",
                        false),
                new FieldDefinition(22, "KVP_STONAD",
                        "Integer",
                        "textBox",
                        94, 100,
                        List.of(),
                        "",
                        false),
                new FieldDefinition(24, "STATUS",
                        "String",
                        "dropDownList",
                        101, 101,
                        List.of(
                                new Code("1", "Deltakeren er fortsatt i program (skjema er ferdig utfylt)"),
                                new Code("2", "Deltakeren er i permisjon fra program (skjemaet er ferdig utfylt)"),
                                new Code("3", "Deltakeren har fullført program eller avsluttet program etter avtale (gjelder ikke flytting)"),
                                new Code("4", "Deltakerens program er varig avbrutt på grunn av uteblivelse (gjelder ikke flytting)"),
                                new Code("5", "Deltakerens program ble avbrutt på grunn av flytting til annen kommune"),
                                new Code("6", "Kun for Oslos bydeler: Deltakeren flyttet til annen bydel før programperioden var over")),
                        "",
                        false),
                new FieldDefinition(25, "AVSL_DATO",
                        "Date",
                        "textBox",
                        102, 107,
                        List.of(),
                        "ddMMyy",
                        false),
                new FieldDefinition(261, "AVSL_ORDINAERTARB",
                        "String",
                        "checkBox",
                        108, 109,
                        List.of(
                                new Code("01", "Ordinært arbeid (heltid/deltid)")),
                        "",
                        false),
                new FieldDefinition(262, "AVSL_ARBLONNSTILS",
                        "String",
                        "checkBox",
                        110, 111,
                        List.of(
                                new Code("11", "Ordinært arbeid (heltid/deltid) med midlertidig lønnstilskudd (jamfør tiltaksforskriften)")),
                        "",
                        false),
                new FieldDefinition(263, "AVSL_ARBMARK",
                        "String",
                        "checkBox",
                        112, 113,
                        List.of(
                                new Code("03", " Andre arbeidsmarkedstiltak i statlig regi (jamfør tiltaksforskriften)")),
                        "",
                        false),
                new FieldDefinition(264, "AVSL_SKOLE",
                        "String",
                        "checkBox",
                        114, 115,
                        List.of(
                                new Code("04", "Skole/utdanning")),
                        "",
                        false),
                new FieldDefinition(265, "AVSL_UFORE",
                        "String",
                        "checkBox",
                        116, 117,
                        List.of(
                                new Code("13", "Uføretrygd")),
                        "",
                        false),
                new FieldDefinition(266, "AVSL_AAP",
                        "String",
                        "checkBox",
                        118, 119,
                        List.of(
                                new Code("14", "Arbeidsavklaringspenger")),
                        "",
                        false),
                new FieldDefinition(267, "AVSL_OK_AVKLAR",
                        "String",
                        "checkBox",
                        120, 121,
                        List.of(
                                new Code("15", "Økonomisk sosialhjelp i påvente av avklaring av uføretrygd/AAP")),
                        "",
                        false),
                new FieldDefinition(268, "AVSL_UTEN_OK_AVKLAR",
                        "String",
                        "checkBox",
                        122, 123,
                        List.of(
                                new Code("16", "Økonomisk sosialhjelp uten slik avklaring")),
                        "",
                        false),
                new FieldDefinition(269, "AVSL_ANNET",
                        "String",
                        "checkBox",
                        124, 125,
                        List.of(
                                new Code("10", "Annet")),
                        "",
                        false),
                new FieldDefinition(2611, "AVSL_UKJENT",
                        "String",
                        "checkBox",
                        126, 127,
                        List.of(
                                new Code("17", "Ukjent")),
                        "",
                        false),
                new FieldDefinition(2612, "AVSL_VIKTIGSTE_INNTEKT",
                        "String",
                        "dropDownList",
                        128, 129,
                        List.of(
                                new Code("01", "Ordinært arbeid (heltid/deltid)"),
                                new Code("11", "Ordinært arbeid (heltid/deltid) med midlertidig lønnstilskudd (jamfør tiltaksforskriften)"),
                                new Code("03", "Andre arbeidsmarkedstiltak i statlig regi (jamfør tiltaksfororskriften) (tiltakspenger)"),
                                new Code("04", "Skole/utdanning (studiestønad)"),
                                new Code("13", "Uføretrygd"),
                                new Code("14", "Arbeidsavklaringspenger"),
                                new Code("15", "Økonomisk sosialhjelp i påvente av avklaring av uføretrygd/AAP"),
                                new Code("16", "Økonomisk sosialhjelp uten slik avklaring"),
                                new Code("10", "Annet"),
                                new Code("17", "Ukjent")),
                        "",
                        false),
                new FieldDefinition(27, "SAKSBEHANDLER",
                        "String",
                        "textBox",
                        130, 139,
                        List.of(),
                        "",
                        false)

        );
    }

    public static Integer getFieldLength() {
        return getFieldDefinitions().get(getFieldDefinitions().size() - 1).getTo();
    }
}