micronaut:
  application:
    name: kostra-kontrollprogram-web

  views:
    folder: static

  router:
    static-resources:
      default:
        enabled: true
        mapping: /**/*
        paths:
          - classpath:static

      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

  server:
    multipart:
      max-file-size: 10485760 # 10 MiB

netty:
  default:
    allocator:
      max-order: 3

api:
  title: "Kostra Kontrollprogram API"
  version: "1.0"
  description: "API for Kostra Kontrollprogram web-applikasjon"