package no.ssb.kostra.area.sosial.sosialhjelp

object SosialhjelpColumnNames {
    const val SAKSBEHANDLER_COL_NAME = "SAKSBEHANDLER"
    const val PERSON_JOURNALNR_COL_NAME = "PERSON_JOURNALNR"
    const val PERSON_FODSELSNR_COL_NAME = "PERSON_FODSELSNR"
    const val PERSON_DUF_COL_NAME = "PERSON_DUFNR"

    const val KOMMUNE_NR_COL_NAME = "KOMMUNE_NR"
    const val BYDELSNR_COL_NAME = "BYDELSNR"
    const val DISTRIKTSNR_COL_NAME = "DISTRIKTSNR"
    const val VERSION_COL_NAME = "VERSION"

    const val KJONN_COL_NAME = "KJONN"
    const val STATUS_COL_NAME = "STATUS"

    // CR NOTE: Only in use in tests
    const val AVSL_DATO_COL_NAME = "AVSL_DATO"
    const val EKTSTAT_COL_NAME = "EKTSTAT"

    const val HAR_BARN_UNDER_18_COL_NAME = "BU18"
    const val ANT_BARN_UNDER_18_COL_NAME = "ANTBU18"

    const val VKLO_COL_NAME = "VKLO"
    const val TRYGDESIT_COL_NAME = "TRYGDESIT"
    const val ARBSIT_COL_NAME = "ARBSIT"

    const val STMND_1_COL_NAME = "STMND_1"
    const val STMND_2_COL_NAME = "STMND_2"
    const val STMND_3_COL_NAME = "STMND_3"
    const val STMND_4_COL_NAME = "STMND_4"
    const val STMND_5_COL_NAME = "STMND_5"
    const val STMND_6_COL_NAME = "STMND_6"
    const val STMND_7_COL_NAME = "STMND_7"
    const val STMND_8_COL_NAME = "STMND_8"
    const val STMND_9_COL_NAME = "STMND_9"
    const val STMND_10_COL_NAME = "STMND_10"
    const val STMND_11_COL_NAME = "STMND_11"
    const val STMND_12_COL_NAME = "STMND_12"

    const val BIDRAG_COL_NAME = "BIDRAG"
    const val BIDRAG_1_COL_NAME = "BIDRAG_1"
    const val BIDRAG_2_COL_NAME = "BIDRAG_2"
    const val BIDRAG_3_COL_NAME = "BIDRAG_3"
    const val BIDRAG_4_COL_NAME = "BIDRAG_4"
    const val BIDRAG_5_COL_NAME = "BIDRAG_5"
    const val BIDRAG_6_COL_NAME = "BIDRAG_6"
    const val BIDRAG_7_COL_NAME = "BIDRAG_7"
    const val BIDRAG_8_COL_NAME = "BIDRAG_8"
    const val BIDRAG_9_COL_NAME = "BIDRAG_9"
    const val BIDRAG_10_COL_NAME = "BIDRAG_10"
    const val BIDRAG_11_COL_NAME = "BIDRAG_11"
    const val BIDRAG_12_COL_NAME = "BIDRAG_12"

    const val LAAN_COL_NAME = "LAAN"
    const val LAAN_1_COL_NAME = "LAAN_1"
    const val LAAN_2_COL_NAME = "LAAN_2"
    const val LAAN_3_COL_NAME = "LAAN_3"
    const val LAAN_4_COL_NAME = "LAAN_4"
    const val LAAN_5_COL_NAME = "LAAN_5"
    const val LAAN_6_COL_NAME = "LAAN_6"
    const val LAAN_7_COL_NAME = "LAAN_7"
    const val LAAN_8_COL_NAME = "LAAN_8"
    const val LAAN_9_COL_NAME = "LAAN_9"
    const val LAAN_10_COL_NAME = "LAAN_10"
    const val LAAN_11_COL_NAME = "LAAN_11"
    const val LAAN_12_COL_NAME = "LAAN_12"

    const val GITT_OKONOMIRAD_COL_NAME = "GITT_OKONOMIRAD"
    const val FAAT_INDIVIDUELL_PLAN_COL_NAME = "FAAT_INDIVIDUELL_PLAN"
    const val BOSIT_COL_NAME = "BOSIT"
    const val VILKARSOSLOV_COL_NAME = "VILKARSOSLOV"
    const val VILKARSAMEKT_COL_NAME = "VILKARSAMEKT"
    const val UTBETDATO_COL_NAME = "UTBETDATO"
    const val UTBETTOMDATO_COL_NAME = "UTBETTOMDATO"
    const val VILKARARBEID_COL_NAME = "VILKARARBEID"
    const val VILKARKURS_COL_NAME = "VILKARKURS"
    const val VILKARUTD_COL_NAME = "VILKARUTD"
    const val VILKARJOBBLOG_COL_NAME = "VILKARJOBBLOG"
    const val VILKARJOBBTILB_COL_NAME = "VILKARJOBBTILB"
    const val VILKARSAMT_COL_NAME = "VILKARSAMT"
    const val VILKAROKRETT_COL_NAME = "VILKAROKRETT"
    const val VILKARLIVSH_COL_NAME = "VILKARLIVSH"
    const val VILKARHELSE_COL_NAME = "VILKARHELSE"
    const val VILKARANNET_COL_NAME = "VILKARANNET"
    const val VILKARDIGPLAN_COL_NAME = "VILKARDIGPLAN"
    const val VILKARNORSKSAMISKOPPL_COL_NAME = "VILKARNORSKSAMISKOPPL"
    const val VEDTAKDATO_COL_NAME = "VEDTAKDATO"
    const val VEDTAKARB_COL_NAME = "VEDTAKARB"
    const val VEDTAKAKT_COL_NAME = "VEDTAKAKT"
    const val VEDTAKHELSE_COL_NAME = "VEDTAKHELSE"
    const val VEDTAKGRUNN_COL_NAME = "VEDTAKGRUNN"
    const val SANKSJONRED_COL_NAME = "SANKSJONRED"
    const val SANKSJONANDRE_COL_NAME = "SANKSJONANDRE"


}