name: Build and deploy
on:
  workflow_dispatch:

  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write

env:
  REGISTRY: europe-north1-docker.pkg.dev/artifact-registry-5n/kostra-docker
  IMAGE: kostra-kontrollprogram

jobs:
  setup:
    name: Setup global environment variable
    environment: setup
    runs-on: ubuntu-24.04
      # Map a step output to a job output
    outputs:
      docker-image: ${{ steps.setup.outputs.image }}
    steps:
      - name: Create and store image tag
        id: setup
        run: echo "image=${REGISTRY}/${IMAGE}:$(date +'%Y%m%d')-${{github.run_number}}" >> "$GITHUB_OUTPUT"

      - name: Echo image tag
        run: echo ${{ steps.setup.outputs.image }}

  docker_build:
    name: Create Docker image
    environment: build
    runs-on: ubuntu-24.04
    needs: setup
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Set up gradle # v5.0.0
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build with Gradle
        run: ./gradlew build -p web --no-daemon --build-cache --info

      - name: Authenticate to Google Cloud # v3.0.0
        id: "auth"
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093
        with:
          workload_identity_provider: "projects/${{ vars.GAR_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gh-actions/providers/gh-actions"
          service_account: "gh-actions-kostra@${{ vars.GAR_PROJECT_ID }}.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: Login to registry # v3.6.0
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4
        with:
          registry: ${{ env.REGISTRY }}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Build and push Docker images # v6.18.0
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          context: ./web
          push: true
          provenance: false
          salsa: true
          tags: |
            ${{needs.setup.outputs.docker-image}}
          team: kostra

  test_deploy:
    name: Deploy to NAIS test
    environment: test
    runs-on: ubuntu-24.04
    needs: [setup, docker_build]
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Deploy to NAIS Test # v2
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: test
          RESOURCE: .nais/test.yaml
          VAR: image=${{needs.setup.outputs.docker-image}}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
