name: Build and deploy
on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  build:
    name: Build
    environment: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Set up Main caching for Gradle and Maven
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: gradle-main-${{ hashFiles('**/*.gradle*', '**/gradle/libs.versions.toml', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-main-

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093
        with:
          token_format: access_token
          workload_identity_provider: "projects/${{ secrets.GAR_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gh-actions/providers/gh-actions"
          service_account: "gh-actions-dftjen@${{ secrets.GAR_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Login to Artifact Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: europe-north1-docker.pkg.dev/${{ secrets.NAIS_MANAGEMENT_PROJECT_ID }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build with Gradle
        run: ./gradlew build --configuration-cache --parallel --build-cache --warn

      - name: Build Docker image Kostra Kontrollprogram Web
        id: docker-build-web
        uses: nais/docker-build-push@751a312f0803eb96a05a41fadf51be19b7be362c
        with:
          team: dftjen
          docker_context: ./web
          pull: false
          image_suffix: "web"
          tag: |
            ${{ github.sha }}
            latest

      - name: Deploy Kostra Kontrollprogram Web to TEST
        uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb
        env:
          CLUSTER: test
          RESOURCE: .nais/web-test.yaml
          NAMESPACE: dftjen
          WORKLOAD_IMAGE: ${{ steps.docker-build-web.outputs.image }}
          TELEMETRY: ${{ steps.docker-build-web.outputs.telemetry }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443

      - name: Build Docker image Kostra Kontrollprogram Altinn API
        id: docker-build-altinn-api
        uses: nais/docker-build-push@751a312f0803eb96a05a41fadf51be19b7be362c
        with:
          team: dftjen
          docker_context: ./altinn-api
          pull: false
          image_suffix: "altinn-api"
          tag: |
            ${{ github.sha }}
            latest

      - name: Deploy Kostra Kontrollprogram Altinn API to TEST
        uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb
        env:
          CLUSTER: test
          RESOURCE: .nais/altinn-api-test.yaml
          NAMESPACE: dftjen
          WORKLOAD_IMAGE: ${{ steps.docker-build-altinn-api.outputs.image }}
          TELEMETRY: ${{ steps.docker-build-altinn-api.outputs.telemetry }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443

      - name: Deployment Summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **SHA**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **URL**: [View Kostra Kontrollprogram](https://kostra-kontrollprogram.intern.test.ssb.no)" >> $GITHUB_STEP_SUMMARY
          echo "- **URL**: [View Altinn API](https://https://kostra-kontrollprogram-altinn-api.intern.test.ssb.no)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
