name: Create release

on:
  release:
    types:
      - released
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set version with Maven
        run: mvn --batch-mode -U versions:set -DnewVersion=${{github.ref_name}}

      - name: Build with Maven
        run: mvn --batch-mode -P github -Drevision=${{github.ref_name}} package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./konsoll/target/jar/kostra-kontrollprogram-${{github.ref_name}}.jar
            ./web/target/jar/kostra-kontrollprogram-web-${{github.ref_name}}.jar
