name: Create pre-release

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Output tag name
        run: echo "github.ref_name = ${{github.ref_name}}"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -Drevision=${{github.ref_name}} package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/jar/kostra-kontrollprogram-${{github.ref_name}}.jar