name: Create pre-release

on:
  push:
    tags:
      - "pre-release-v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -P github -Drevision=${{github.ref_name}} package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./konsoll/target/jar/kostra-kontrollprogram-${{github.ref_name}}.jar
