package no.ssb.kostra.control;

import javax.swing.*;
import java.awt.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintStream;


public class TestGui5 extends JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 5523226588856551943L;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton4;
    private JComboBox<String> jComboBox1;
    private JComboBox<String> jComboBox2;
    private JComboBox<String> jComboBox3;
    private JComboBox<String> jComboBox4;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JSplitPane jSplitPane1;
    private JTextArea jTextArea1;
    private JTextArea jTextArea2;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private JTextField jTextField3;
    private JTextField jTextField4;
    private JTextField txtKontorNr;
    /**
     * Creates new form TestGui5
     */
    public TestGui5() {
        initComponents();
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Årsregnskap");
        jComboBox1.addItem("Kvartalsregnskap");
        jComboBox1.addItem("Sosialhjelp 11");
        jComboBox1.addItem("Kvalifiseringsstønad 11C");
        jComboBox1.addItem("Barnevern 15");
        jComboBox1.addItem("Familievern 52A");
        jComboBox1.addItem("Familievern 52B");
        jComboBox1.addItem("Familievern 53");
        jComboBox1.addItem("Meklinger 55");

        jComboBox2.addItem("0A");
        jComboBox2.addItem("0B");
        jComboBox2.addItem("0C");
        jComboBox2.addItem("0D");
        jComboBox2.addItem("0I");
        jComboBox2.addItem("0J");
        jComboBox2.addItem("0K");
        jComboBox2.addItem("0L");
        jComboBox2.addItem("0M");
        jComboBox2.addItem("0N");
        jComboBox2.addItem("0P");
        jComboBox2.addItem("0Q");
        jComboBox2.addItem("0F");
        jComboBox2.addItem("0G");
        jComboBox2.addItem("0X");
        jComboBox2.addItem("0Y");
        jComboBox2.setVisible(false);

        jComboBox3.addItem("0A");
        jComboBox3.addItem("0B");
        jComboBox3.addItem("0C");
        jComboBox3.addItem("0D");
        jComboBox3.setVisible(false);

        jComboBox4.addItem("1. kvartal");
        jComboBox4.addItem("2. kvartal");
        jComboBox4.addItem("3. kvartal");
        jComboBox4.addItem("4. kvartal");
        jComboBox4.setVisible(false);

        jLabel2.setVisible(false);
        txtKontorNr.setVisible(false);

        setTitle("Test av kontrollprogram for " + Constants.kostraYear + "-rapporteringen");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new TestGui5().setVisible(true));
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new JPanel();
        jTextField1 = new JTextField();
        jTextField2 = new JTextField();
        jLabel1 = new JLabel();
        txtKontorNr = new JTextField("");
        jLabel2 = new JLabel();
        jComboBox1 = new JComboBox<>();
        jLabel3 = new JLabel();
        jTextField3 = new JTextField();
        jLabel4 = new JLabel();
        jTextField4 = new JTextField();
        jLabel5 = new JLabel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jComboBox2 = new JComboBox<>();
        jComboBox3 = new JComboBox<>();
        jComboBox4 = new JComboBox<>();
        jPanel2 = new JPanel();
        jButton3 = new JButton();
        jButton4 = new JButton();
        jPanel3 = new JPanel();
        jSplitPane1 = new JSplitPane();
        jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();
        jScrollPane2 = new JScrollPane();
        jTextArea2 = new JTextArea();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Region (6 siffer)");

        jLabel2.setText("Kontornr.");

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel3.setText("Type");

        jLabel4.setText("Kildefil/filuttrekk");

        jLabel5.setText("Rapportfil");

        jButton1.setText("Velg...");
        jButton1.addActionListener(this::velgKildefil);

        jButton2.setText("Velg...");
        jButton2.addActionListener(this::velg_rapportfil);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jLabel4)
                                        .add(jLabel5)
                                        .add(jLabel1))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jPanel1Layout.createSequentialGroup()
                                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                        .add(jTextField4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                                                        .add(jTextField3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                                        .add(jPanel1Layout.createSequentialGroup()
                                                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(35, 35, 35)
                                                .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(35, 35, 35)
                                                .add(jLabel3)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 319, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(22, 22, 22)
                                                .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(15, 15, 15)
                                                .add(jComboBox4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                                                .add(jLabel2)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(txtKontorNr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(26, 26, 26)))
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jButton2)
                                        .add(jButton1))
                                .add(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                                .add(19, 19, 19)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jLabel1)
                                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jLabel3)
                                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jLabel2)
                                        .add(txtKontorNr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jComboBox4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(14, 14, 14)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jLabel4)
                                        .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jButton1))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jLabel5)
                                        .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(jButton2))
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jButton3.setText("Kj\u00f8r kontroll");
        jButton3.addActionListener(this::kjor_kontroll);

        jButton4.setText("Avslutt");
        jButton4.setToolTipText("Avslutt programmet.");
        jButton4.addActionListener(this::avslutt);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(730, Short.MAX_VALUE)
                                .add(jButton3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButton4)
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(42, Short.MAX_VALUE)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(jButton4)
                                        .add(jButton3))
                                .add(35, 35, 35))
        );
        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jSplitPane1.setRightComponent(jScrollPane2);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                .addContainerGap())
        );
        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getItemAt(jComboBox1.getSelectedIndex()) != null) {
            jComboBox2.setVisible((jComboBox1.getItemAt(jComboBox1.getSelectedIndex())).equalsIgnoreCase("Årsregnskap"));
            jComboBox3.setVisible((jComboBox1.getItemAt(jComboBox1.getSelectedIndex())).equalsIgnoreCase("Kvartalsregnskap"));
            jComboBox4.setVisible((jComboBox1.getItemAt(jComboBox1.getSelectedIndex())).equalsIgnoreCase("Kvartalsregnskap"));
            jLabel2.setVisible((jComboBox1.getItemAt(jComboBox1.getSelectedIndex())).startsWith("Familievern"));
            txtKontorNr.setVisible((jComboBox1.getItemAt(jComboBox1.getSelectedIndex())).startsWith("Familievern"));
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void kjor_kontroll(java.awt.event.ActionEvent evt)//GEN-FIRST:event_kjor_kontroll
    {//GEN-HEADEREND:event_kjor_kontroll

        if (jTextField1.getText().equalsIgnoreCase("")) {
            showErrorDialog("Angi kommunenr+bydelsnr.");
            return;
        } else if (jTextField3.getText().equalsIgnoreCase("")) {
            showErrorDialog("Angi kildefil.");
            return;
        } else if (jTextField4.getText().equalsIgnoreCase("")) {
            showErrorDialog("Angi rapportfil.");
            return;
        }

//      int error_type_found;
//      String NO_DATA_FOUND = "\n\n\tFEIL SOM HINDRER INNSENDING ER FUNNET!";

//      PrintStream pso = System.out;
        ByteArrayOutputStream byo = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(byo);
        System.setOut(ps);

        try {
            BufferedWriter wr = new BufferedWriter(new FileWriter(getOutfile()));
            wr.write("");
            wr.close();

            if (((String) jComboBox1.getSelectedItem()).equalsIgnoreCase("Årsregnskap")) {
//          error_type_found =
                new ControlProgram().doControl(new String[]{jTextField1.getText(),
                        getInfile(), getOutfile(), Integer.toString(ControlProgram.REGNSKAP), (String) jComboBox2.getSelectedItem(), jTextField2.getText()});
//          if (error_type_found == Constants.CRITICAL_ERROR)
//            showErrorDialog (NO_DATA_FOUND);
            } else if (((String) jComboBox1.getSelectedItem()).equalsIgnoreCase("Kvartalsregnskap")) {
//          error_type_found =
                new ControlProgram().doControl(new String[]{jTextField1.getText(),
                        getInfile(), getOutfile(), Integer.toString(ControlProgram.REGNSKAP), jComboBox3.getSelectedItem() + "K" + ((String) jComboBox4.getSelectedItem()).substring(0, 1), jTextField2.getText()});
//          if (error_type_found == Constants.CRITICAL_ERROR)
//            showErrorDialog (NO_DATA_FOUND);
            } else if (((String) jComboBox1.getSelectedItem()).equalsIgnoreCase("Sosialhjelp 11")) {
//          error_type_found =
                new ControlProgram().doControl(new String[]{jTextField1.getText(),
                        getInfile(), getOutfile(), Integer.toString(ControlProgram.SOSIALHJELP), jTextField2.getText()});
//          if (error_type_found == Constants.CRITICAL_ERROR)
//            showErrorDialog (NO_DATA_FOUND);
            } else if (((String) jComboBox1.getSelectedItem()).equalsIgnoreCase("Kvalifiseringsstønad 11C")) {
//          error_type_found =
                new ControlProgram().doControl(new String[]{jTextField1.getText(),
                        getInfile(), getOutfile(), Integer.toString(ControlProgram.KVALIFISERINGSSTONAD), jTextField2.getText()});
//          if (error_type_found == Constants.CRITICAL_ERROR)
//            showErrorDialog (NO_DATA_FOUND);
            } else if (((String) jComboBox1.getSelectedItem()).equalsIgnoreCase("Barnevern 15")) {
//          error_type_found =
                new ControlProgram().doControl(new String[]{jTextField1.getText(),
                        getInfile(), getOutfile(), Integer.toString(ControlProgram.BARNEVERN), jTextField2.getText()});
//          if (error_type_found == Constants.CRITICAL_ERROR)
//            showErrorDialog (NO_DATA_FOUND);
            } else if (((String) jComboBox1.getSelectedItem()).equalsIgnoreCase("Familievern 52A")) {
//          error_type_found =
                new ControlProgram().doControl(new String[]{jTextField1.getText(),
                        getInfile(), getOutfile(), Integer.toString(ControlProgram.FAMILIEVERN), txtKontorNr.getText(), jTextField2.getText()});
            } else if (((String) jComboBox1.getSelectedItem()).equalsIgnoreCase("Familievern 52B")) {
//          error_type_found =
                new ControlProgram().doControl(new String[]{jTextField1.getText(),
                        getInfile(), getOutfile(), Integer.toString(ControlProgram.FAMILIEVERN_B), txtKontorNr.getText(), jTextField2.getText()});
            } else if (((String) jComboBox1.getSelectedItem()).equalsIgnoreCase("Familievern 53")) {
//          error_type_found =
                new ControlProgram().doControl(new String[]{jTextField1.getText(),
                        getInfile(), getOutfile(), Integer.toString(ControlProgram.FAMILIEVERN_53), txtKontorNr.getText(), jTextField2.getText()});
            } else if (((String) jComboBox1.getSelectedItem()).equalsIgnoreCase("Meklinger 55")) {
//          error_type_found =
                new ControlProgram().doControl(new String[]{jTextField1.getText(),
                        getInfile(), getOutfile(), Integer.toString(ControlProgram.Meklinger_55), jTextField2.getText()});
//              getInfile(), getOutfile(),Integer.toString(ControlProgram.Meklinger_55), txtKontorNr.getText()});
            }

            BufferedReader fileReader = new BufferedReader(new FileReader(getOutfile()));
            String line;
            StringBuffer buffer = new StringBuffer();
            while ((line = fileReader.readLine()) != null) {
                buffer.append(line);
                buffer.append("\n");
            }
            fileReader.close();
            Font f = new Font("Courier", Font.PLAIN, 12);
            jTextArea2.setFont(f);
            jTextArea2.setText(buffer.toString());
            jTextArea2.setCaretPosition(0);

            fileReader = new BufferedReader(new FileReader(getInfile()));
            buffer = new StringBuffer();
            int lineNo = 1;
            while ((line = fileReader.readLine()) != null) {
                buffer.append(lineNo++);
                buffer.append(":\t");
                buffer.append(line);
                buffer.append("\n");
            }
            fileReader.close();
            jTextArea1.setFont(f);
            jTextArea1.setText(buffer.toString());
            jTextArea1.setCaretPosition(0);

            jTextArea2.requestFocus();

            String tmp = jTextArea2.getText();
            jTextArea2.setText(byo.toString() + tmp);

        } catch (Exception ex) {
            ex.printStackTrace();
            showErrorDialog(ex.toString());
        }
    }//GEN-LAST:event_kjor_kontroll

    private void velg_rapportfil(java.awt.event.ActionEvent evt)//GEN-FIRST:event_velg_rapportfil
    {//GEN-HEADEREND:event_velg_rapportfil
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(".")); //C:/KODE/KOSTRA/Workspace1/Kontrollprogram05/testfiler"));
        fc.setDialogTitle("Velg rapportfil");
        int returnValue = fc.showSaveDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            jTextField4.setText(fc.getSelectedFile().getAbsolutePath());
        }

    }//GEN-LAST:event_velg_rapportfil

    private void avslutt(java.awt.event.ActionEvent evt)//GEN-FIRST:event_avslutt
    {//GEN-HEADEREND:event_avslutt
        System.exit(0);
    }//GEN-LAST:event_avslutt

    private void velgKildefil(java.awt.event.ActionEvent evt)//GEN-FIRST:event_velgKildefil
    {//GEN-HEADEREND:event_velgKildefil
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("Q:/DOK/KOSTRA/KOSTRA-kommune og Fylkes-KOSTRA/Arbeidsområde/Filuttrekk/Kravspec/Kontrollprogram"));
//        fc.setCurrentDirectory(new File("Q:/DOK/KOSTRA/StatsKOSTRA/Helseforetak/Kravspesifikasjon2011/Tilleggsskjema Testfiler"));
        fc.setDialogTitle("Velg kildefil (filuttrekk)");
        int returnValue = fc.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            jTextField3.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_velgKildefil

    private String getInfile() {
        File f = new File(jTextField3.getText());
        return f.getAbsolutePath();
    }

    private String getOutfile() {
        File f = new File(jTextField4.getText());
        return f.getAbsolutePath();
    }

    private void showErrorDialog(String msg) {
        JDialog errDialog = new JDialog();
        errDialog.setSize(640, 480);
        errDialog.setTitle("Melding fra kontrollprogrammet:");
        JTextArea textArea = new JTextArea();
        textArea.setLineWrap(true);
        textArea.setText(msg);
        errDialog.add(textArea);
        errDialog.setVisible(true);
    }
    // End of variables declaration//GEN-END:variables

}
